version: '3.9'

volumes:
  pgdata:

networks:
  backend:


services:
  python_app:
    build: .
    networks:
      - backend
    env_file:
      - .env
    ports:
      - "8080:8000"
    depends_on:
      - postgredb
    command: python manage.py runserver 0.0.0.0:8000

  postgredb:
    image: postgres:latest
    networks:
      - backend
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=2022
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my_db"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    volumes:
      - .:/logs:/var/log
      - pgdata:/var/lib/postgresql/data
      - .:/docker-entrypoint-initdb.b
  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - backend
    environment:
      - PGADMIN_DEFAULT_EMAIL=arturtref@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G